CREATE TABLE IF NOT EXISTS users (
  id VARCHAR(255) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NUlL,
  phone VARCHAR(255) UNIQUE NUll,
  imageUrl VARCHAR(255) NULL,
  friendCount INTEGER DEFAULT 0
);
